liip_imagine:
    driver: "gd"
    
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'

    # Ajout pour corriger les dépréciations Twig
    twig:
        mode: lazy

    filter_sets:
        thumb_small:
            quality: 82
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
            # post_processors: # Commenté car strip n'est pas disponible avec GD

        thumb_medium:
            quality: 82
            filters:
                thumbnail: { size: [500, 375], mode: outbound }
            # post_processors:

        thumb_large:
            quality: 80
            filters:
                thumbnail: { size: [800, 450], mode: outbound }
            # post_processors:

        thumb_hero:
            quality: 78
            filters:
                thumbnail: { size: [1200, 630], mode: outbound }
            # post_processors: