framework:
    default_locale: 'fr'
    enabled_locales: ['fr', 'en', 'sw']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            fr: 'fr'
            en: 'en'
            sw: 'sw'
        providers:
